name: Docker Image CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.ACRUSERNAME2 }}
          DOCKER_PASSWORD: ${{ secrets.ACRPASSWORD2 }}
          DOCKER_REGISTRY_URL: millerbacr.azurecr.io

      - name: Build image
        if: success()
        run: docker build --file Dockerfile --tag millerbacr.azurecr.io/sqlpackage:latest .

      - name: Test Docker Image
        if: success()
        run: docker run --rm millerbacr.azurecr.io/sqlpackage:latest sqlpackage /help
      
      - name: Push Docker Image
        if: success()
        run: docker push millerbacr.azurecr.io/sqlpackage:latest
